// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("rescript/lib/js/array.js");
var Process = require("process");
var Caml_splice_call = require("rescript/lib/js/caml_splice_call.js");

function run(param) {
  var input = Process.argv.slice(2, Process.argv.length);
  var output = $$Array.map((function (word) {
          return word.replace(/l|i/gi, "1").replace(/z|r/gi, "2").replace(/e/gi, "3").replace(/a/gi, "4").replace(/s/gi, "5").replace(/G/g, "6").replace(/t/gi, "7").replace(/b/gi, "8").replace(/g/g, "9").replace(/o/gi, "0");
        }), input);
  Caml_splice_call.spliceApply(console.log, [output]);
  
}

exports.run = run;
/* process Not a pure module */
